### ISSUE TITLE
How to start the training process?

### ISSUE THREAD

**Issue by jocacace** [adipandas/gym_multirotor#1]
Hi guys, 

I am quite new of mujoco environments. I should have correctly installed all the dependencies of the gym_multirotor software. However, I am not able to find doc on how to start the training process. I am trying to train the flat quadrotor (no matter if it a plus or X conf). 

I run the following code:

$ python3 quadrotor_plus_hover.py 

However, nothing happen after this command. I startes as standalone the mujoco xml simulation files and everything is correct.

How is supposed to start the training process?

Cheers,

**Comment by adipandas** [comment]
You will need to write the policy and optimization routine (some RL algorithm). I recommend to use [stable-baselines](https://github.com/DLR-RM/stable-baselines3) and add this environment over there.
