### ISSUE TITLE
envs usage

### ISSUE THREAD

**Issue by AlmeidaAlin3** [adipandas/gym_multirotor#2]
Hi adipandas! :)
I've read you papers and loved them! I'm starting to learn how to work with Mujoco and RL. Could you please tell me how can I use your files? I'm able to see your .xml files in my Mujoco simulator (because I dragged them into Mujoco), but I don't know how to make it work according to your .py files.
Thank you!

**Comment by adipandas** [comment]
Sorry for the delay. Couldn't find time to update my GitHub. I have updated the codes now.
Thank you.
