### ISSUE TITLE
code for reproducing the plots

### ISSUE THREAD

**Issue by AlmeidaAlin3** [adipandas/gym_multirotor#3]
Hi, I was wondering if you could please help with the code for getting the plots similar to the ones that were published in the paper for trajectory, position variation, euler angles, tilt angles and waypoint navigation? I'm doing a similar work and would love to compare with your results.

**Comment by adipandas** [comment]
please refer [this](https://github.com/adipandas/gym_multirotor/blob/main/gym_multirotor/utils/plotters.py) for plotting.
