### ISSUE TITLE
PPO training code

### ISSUE THREAD

**Issue by AlmeidaAlin3** [adipandas/gym_multirotor#4]
Could also be possible to share your training file for the PPO algorithm you've used?

**Comment by adipandas** [comment]
Hello @AlmeidaAlin3 I have included training using [stable-baselines3](https://stable-baselines3.readthedocs.io/). I have included the trained policies as well. 
For the paper, I used [this implementation](https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail.git) for training of stable policies. But now it is legacy and I have removed it. You should be able to replace the parameters in the policy using [get_parameters](https://stable-baselines3.readthedocs.io/en/master/modules/base.html#stable_baselines3.common.base_class.BaseAlgorithm.get_parameters) and [set_parameters](https://stable-baselines3.readthedocs.io/en/master/modules/base.html#stable_baselines3.common.base_class.BaseAlgorithm.set_parameters) in [stable-baselines3](https://stable-baselines3.readthedocs.io/) for training policy similar to my research papers.

P.S. It has been a while I used this repo. Thanks for bringing this up! It motivated me to update the codes. :sweat_smile: 
I hope you find my work helpful/useful.

**Comment by adipandas** [comment]
@AlmeidaAlin3 codes for results from paper are available [here](https://github.com/adipandas/gym_multirotor/tree/main/examples/rl/experiments_from_paper)
